added flake for code quality check

diff --git a/messaging_app/messaging_app/.github/workflows/ci.yml b/messaging_app/messaging_app/.github/workflows/ci.yml
--- a/messaging_app/messaging_app/.github/workflows/ci.yml
+++ b/messaging_app/messaging_app/.github/workflows/ci.yml
@@ -55,6 +55,18 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
+      - name: Lint with flake8
+        run: |
+          echo "Running flake8..."
+          flake8 messaging_app --count --select=E9,F63,F7,F82 --show-source --statistics
+          flake8 messaging_app --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
+          # Fail the build if there are any lint errors
+          flake8 messaging_app --max-line-length=100 --exit-zero | tee flake8.log
+          if [ -s flake8.log ]; then
+            echo "Flake8 lint errors found."
+            exit 1
+          fi
+
       - name: Wait for MySQL to be ready
         run: |
           until mysqladmin ping -h 127.0.0.1 --silent; do
@@ -66,6 +78,12 @@ jobs:
         run: |
           python manage.py migrate
 
-      - name: Run tests
+      - name: Run tests with coverage
         run: |
-          pytest --ds=messaging_app.settings  # change this if you use a different settings module
+          pytest --cov=messaging_app --cov-report=html --ds=messaging_app.settings
+
+      - name: Upload coverage report
+        uses: actions/upload-artifact@v4
+        with:
+          name: html-coverage-report
+          path: htmlcov
